import { TwaBridgeProvider } from "@/lib/hooks/use-twa-bridge";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Kalnia, Urbanist } from "next/font/google";
import "./globals.css";

const kalnia = Kalnia({ variable: "--font-kalnia", subsets: ["latin"] });
const urbanist = Urbanist({ variable: "--font-urbanist", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="pl">
        <body
          className={`${kalnia.variable} ${urbanist.className} antialiased`}
        >
          <TwaBridgeProvider>{children}</TwaBridgeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
